import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import Navbar from "../component/Navbar";
import Movie from "../component/Movie";
const inter = Inter({ subsets: ["latin"] });
import Slider from "../component/Slider";
import Footer from "../component/Footer";
import db from "../component/Db";
import { collection,getDocs } from "firebase/firestore";
import { useEffect, useState } from "react";
export default function Home() {
 
 
    

  return (
    <>
      <Head>
        <title>BINIMOVIES</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
                 
      <Slider />
      <Movie  />
   
    </>
  );
}
